### ISSUE TITLE
iPhone 7 failed to send iBSS

### ISSUE THREAD

**Issue by krisanovdev** [axi0mX/ipwndfu#128]
Hi, got error while sending iBSS to phone in pwned dfu mode. Any ideas?
`./ipwndfu -f /Users/dev/Desktop/ipsw/Firmware/dfu/iBSS.d20.RELEASE.im4p 
Traceback (most recent call last):
  File "./ipwndfu", line 122, in <module>
    dfu.send_data(device, data)
  File "/Users/dev/Desktop/ipwndfu/dfu.py", line 48, in send_data
    assert device.ctrl_transfer(0x21, 1, 0, 0, data[index:index + amount], 5000) == amount
  File "/Users/dev/Desktop/ipwndfu/usb/core.py", line 1043, in ctrl_transfer
    self.__get_timeout(timeout))
  File "/Users/dev/Desktop/ipwndfu/usb/backend/libusb1.py", line 883, in ctrl_transfer
    timeout))
  File "/Users/dev/Desktop/ipwndfu/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 5] Input/Output Error`

**Comment by synackuk** [comment]
Correct, checkm8 doesn't currently support uploading of iBSS images. [Linus Henze's fork](https://github.com/LinusHenze/ipwndfu_public) fixes this for some devices by adding a SecureROM patcher (though it only supports a limited number of devices).
