### ISSUE TITLE
NoBackendError (Line 48)

### ISSUE THREAD

**Issue by LorcanT** [axi0mX/ipwndfu#167]
Recent error trying to attempt to pwn on MacOS Catalina Beta 10.15.1... (1)
I have ran in relation to the previous issue #11 the command "brew link libusb" (2) and both "brew uninstall libusb" and "brew install libusb" (3)

(1)
Traceback (most recent call last):
  File "./ipwndfu", line 48, in <module>
    device = dfu.acquire_device()
  File "/Users/lorcantuohy/Downloads/ipwndfu-master/dfu.py", line 16, in acquire_device
    for device in usb.core.find(find_all=True, idVendor=0x5AC, idProduct=0x1227, backend=backend):
  File "/Users/lorcantuohy/Downloads/ipwndfu-master/usb/core.py", line 1263, in find
    raise NoBackendError('No backend available')
usb.core.NoBackendError: No backend available

(2)
Error: No such keg: /usr/local/Cellar/libusb

(3)
Warning: You are using macOS 10.15.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience, as you are running this pre-release version.

Error: The following formula
  git
cannot be installed as binary package and must be built from source.
Install the Command Line Tools:
  xcode-select --install

Error: Git must be installed and in your PATH!
Warning: You are using macOS 10.15.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience, as you are running this pre-release version.

Error: The following formula
  libusb
cannot be installed as binary package and must be built from source.
Install the Command Line Tools:
  xcode-select --install

Just wondering does anyone know anything about these issues and wether or not these are know issues... Or am i just stupid?

**Comment by zEstLabs** [comment]
Did you actually try to install Command Line Tools as the error states?

**Comment by LorcanT** [comment]
@zEstLabs Yes same issue occured
