### ISSUE TITLE
ValueError: The device has no langid (iPhone 8 - 10,4)

### ISSUE THREAD

**Issue by kid1carus** [axi0mX/ipwndfu#185]
Attached is the output after running checkm8 on my jailbroken iphone 8 using unc0ver on ios 12.4.

Any solutions to this problem yet?
![Screen Shot 2019-10-23 at 11 00 26 PM](https://user-images.githubusercontent.com/45052773/67629771-5f837180-f851-11e9-8f8e-261ef637ad44.png)

**Comment by izaman1** [comment]
add sudo ./ipwndfu -p then try. Now close this issue

**Comment by imifos** [comment]
Insert
`device._langids = (1033,)`
between 
`for device in usb.core.find(...`
and
`if match is not None...`
at line
https://github.com/axi0mX/ipwndfu/blob/master/dfu.py#L16
see
https://github.com/pyusb/pyusb/issues/139
PS.
No pull request as they don't get merged. Patch can be applied locally.

**Comment by rexsllemel** [comment]
> Insert `device._langids = (1033,)` between `for device in usb.core.find(...` and `if match is not None...` at line https://github.com/axi0mX/ipwndfu/blob/master/dfu.py#L16 see [pyusb/pyusb#139](https://github.com/pyusb/pyusb/issues/139) PS. No pull request as they don't get merged. Patch can be applied locally.

I have this error in ubuntu 20.04
`sudo python2 ipwndfu -p --patch
Traceback (most recent call last):
  File "ipwndfu", line 6, in <module>
    import dfu, nor, utilities
  File "/home/rexsovel/Downloads/ipwndfu-A11-patch-rom/dfu.py", line 17
    device._langids = (1033,)
         ^
IndentationError: expected an indented block`
