### ISSUE TITLE
NoBackendError

### ISSUE THREAD

**Issue by BrayanOfficiel** [axi0mX/ipwndfu#205]
I got this : 
`Traceback (most recent call last):
  File "./ipwndfu", line 48, in <module>
    device = dfu.acquire_device()
  File "/Users/haiderboudjemeline/Desktop/Fichiers/ipwndfu-master/dfu.py", line 16, in acquire_device
    for device in usb.core.find(find_all=True, idVendor=0x5AC, idProduct=0x1227, backend=backend):
  File "/Users/haiderboudjemeline/Desktop/Fichiers/ipwndfu-master/usb/core.py", line 1263, in find
    raise NoBackendError('No backend available')
usb.core.NoBackendError: No backend available`

**Comment by SAYEDALISINA93** [comment]
I have the same issue!

**Comment by LYJSPEEDX** [comment]
install libusb as instructed

**Comment by Direct-A** [comment]
> install libusb as instructed

no use, still the same error

it needs libusb v1.23, after I install it the problem changes

**Comment by burakCokyildirim** [comment]
> install libusb as instructed

this fixed my error, thank you 👍

**Comment by bacid** [comment]
I have the same error. Please a solution how to fix the backend error
