### ISSUE TITLE
iPhone SE (2016) NoBackend Error. Libusb is installed

### ISSUE THREAD

**Issue by JSwamie** [axi0mX/ipwndfu#305]
```
jonah@Jonahs-MBP ipwndfu-master % ./ipwndfu -p
Traceback (most recent call last):
File "./ipwndfu", line 48, in <module>
device = dfu.acquire_device()
File "/Users/jonah/Downloads/ipwndfu-master/dfu.py", line 16, in acquire_device
for device in usb.core.find(find_all=True, idVendor=0x5AC, idProduct=0x1227, backend=backend):
File "/Users/jonah/Downloads/ipwndfu-master/usb/core.py", line 1263, in find
raise NoBackendError('No backend available')
usb.core.NoBackendError: No backend available
```

**Comment by JSwamie** [comment]
Please don't suggest I install libusb since I have already run `brew install libusb` a few times with no success. Unless there is another method of installing it. I checked other tutorials that use `apt-get` to install it but I can't do that on Mac.

**Comment by Harryford1312** [comment]
> ```
> 
> jonah@Jonahs-MBP ipwndfu-master % ./ipwndfu -p
> 
> Traceback (most recent call last):
> 
> File "./ipwndfu", line 48, in <module>
> 
> device = dfu.acquire_device()
> 
> File "/Users/jonah/Downloads/ipwndfu-master/dfu.py", line 16, in acquire_device
> 
> for device in usb.core.find(find_all=True, idVendor=0x5AC, idProduct=0x1227, backend=backend):
> 
> File "/Users/jonah/Downloads/ipwndfu-master/usb/core.py", line 1263, in find
> 
> raise NoBackendError('No backend available')
> 
> usb.core.NoBackendError: No backend available
> 
> ```
