### ISSUE TITLE
No Backend Error (iPhone SE 2016)

### ISSUE THREAD

**Issue by jonahdecker** [axi0mX/ipwndfu#314]
```
Last login: Sun Aug 28 20:54:25 on ttys000
jonahdecker@Jonahs-MBP ~ % cd ipwndfu-master      
jonahdecker@Jonahs-MBP ipwndfu-master % sudo python2 ipwndfu -p
Password:
Traceback (most recent call last):
  File "ipwndfu", line 48, in <module>
    device = dfu.acquire_device()
  File "/Users/jonahdecker/ipwndfu-master/dfu.py", line 16, in acquire_device
    for device in usb.core.find(find_all=True, idVendor=0x5AC, idProduct=0x1227, backend=backend):
  File "/Users/jonahdecker/ipwndfu-master/usb/core.py", line 1263, in find
    raise NoBackendError('No backend available')
usb.core.NoBackendError: No backend available
jonahdecker@Jonahs-MBP ipwndfu-master % 
```

**Comment by iarchiveml** [comment]
Known issue that won't be fixed

**Comment by jonahdecker** [comment]
> Known issue that won't be fixed

Seems lazy. Works on Windows and on macOS with other tools.
