### ISSUE TITLE
ipwndfu -x assertion error

### ISSUE THREAD

**Issue by samueloufc** [axi0mX/ipwndfu#46]
NOR backed up to file: nor-backups/nor-000000D5E9047577-20190324-014439.dump
Traceback (most recent call last):
  File "./ipwndfu", line 77, in <module>
    nor = nor.NorData(dump)
  File "/Users/anthonyfranklin/Desktop/ipwndfu-master/nor.py", line 11, in __init__
    assert img2_crc == binascii.crc32(dump[:48]) & 0xffffffff
AssertionError

here's the error I'm getting

**Comment by debouncedgit** [comment]
This is surely fixed being this was back in March. Please close your issue. Thanks.

**Comment by TheRasPiGuy** [comment]
Actually, this still hasn't been fixed, I'm still getting the error
