### ISSUE TITLE
Help with ipad 2

### ISSUE THREAD

**Issue by Gigabyte2003** [axi0mX/ipwndfu#59]
i have an ipad 2 on ios 6.1.4 and ice managed to get it working without having to change and this keeps happening on the first step
`mac-mini:~ Gigabyte$ ./ipwndfu/ipwndfu -p
Traceback (most recent call last):
  File "./ipwndfu/ipwndfu", line 47, in <module>
    device = dfu.acquire_device()
  File "/Users/Gigabyte/ipwndfu/dfu.py", line 16, in acquire_device
    for device in usb.core.find(find_all=True, idVendor=0x5AC, idProduct=0x1227, backend=backend):
  File "/Users/Gigabyte/ipwndfu/usb/core.py", line 1263, in find
    raise NoBackendError('No backend available')
usb.core.NoBackendError: No backend available
`
any help would well.. help thanks!

**Comment by Gigabyte2003** [comment]
i would also like to note that im very new to this software and legacy jailbreaking in general so im basically your local idiot XD

**Comment by 2Eggsss** [comment]
> i would also like to note that im very new to this software and legacy jailbreaking in general so im basically your local idiot XD

Does the issue appear even if you try to run it as root?

**Comment by Gigabyte2003** [comment]
SEE I AM NEW!!
how did i not think about that? thanks, dude!

**Comment by wholivesinapineappleunderthesea** [comment]
Close issues after they are solved
