### ISSUE TITLE
usb.core.USBError: [Errno 22] Invalid parameter

### ISSUE THREAD

**Issue by 0x06060606** [axi0mX/ipwndfu#86]
```
[root@ArchTop ipwndfu]# ./ipwndfu --dump-rom
Acquiring device handle.
Releasing device handle.
Acquiring device handle.
Releasing device handle.
Acquiring device handle.
Sending 0x10 of data to device.
Sending 0x28 of data to device.
Releasing device handle.
Acquiring device handle.
Sending 0x10 of data to device.
Sending 0x28 of data to device.
Traceback (most recent call last):
  File "./ipwndfu", line 199, in <module>
    securerom = pwned.read_memory(pwned.platform.rom_base, pwned.platform.rom_size)
  File "/root/ipwndfu/usbexec.py", line 89, in read_memory
    response = self.command(self.cmd_memcpy(self.cmd_data_address(0), address + len(data), part_length), self.cmd_data_offset(0) + part_length)
  File "/root/ipwndfu/usbexec.py", line 108, in command
    response = device.ctrl_transfer(0xA1, 2, 0xFFFF, 0, response_length, CMD_TIMEOUT).tostring()
  File "/root/ipwndfu/usb/core.py", line 1043, in ctrl_transfer
    self.__get_timeout(timeout))
  File "/root/ipwndfu/usb/backend/libusb1.py", line 883, in ctrl_transfer
    timeout))
  File "/root/ipwndfu/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 22] Invalid parameter
```

**Comment by 0x06060606** [comment]
*Debugging...

```
[root@ArchTop ipwndfu]# ./ipwndfu --dump-rom
Acquiring device handle.
Releasing device handle.
Acquiring device handle.
Releasing device handle.
Acquiring device handle.
Sending 0x10 of data to device.
Sending 0x28 of data to device.
Releasing device handle.
Acquiring device handle.
Sending 0x10 of data to device.
Sending 0x28 of data to device.
[Errno 22] Invalid parameter
Traceback (most recent call last):
  File "./ipwndfu", line 206, in <module>
    if hashlib.sha1(securerom).hexdigest() != pwned.platform.rom_sha1:
NameError: name 'securerom' is not defined
```

**Comment by ushadowxtw** [comment]
[https://github.com/axi0mX/ipwndfu/issues/72](url)

**Comment by EWouters** [comment]
This issue has been raised before in #72 as @ushadowxtw kindly told you (although he posted a malformed link). Please take a look there and close this issue.
