### ISSUE TITLE
Error when --dump-rom iPad mini 2

### ISSUE THREAD

**Issue by SarasetitheGOD** [axi0mX/ipwndfu#89]
Been trying to put in pwned DFU mode all day and when i finally get it i try yo dump rom and this happens

Traceback (most recent call last):
  File "./ipwndfu", line 199, in <module>
    securerom = pwned.read_memory(pwned.platform.rom_base, pwned.platform.rom_size)
  File "/home/saraseti_sunra/Desktop/checkm8/ipwndfu-master/usbexec.py", line 89, in read_memory
    response = self.command(self.cmd_memcpy(self.cmd_data_address(0), address + len(data), part_length), self.cmd_data_offset(0) + part_length)
  File "/home/saraseti_sunra/Desktop/checkm8/ipwndfu-master/usbexec.py", line 108, in command
    response = device.ctrl_transfer(0xA1, 2, 0xFFFF, 0, response_length, CMD_TIMEOUT).tostring()
  File "/home/saraseti_sunra/Desktop/checkm8/ipwndfu-master/usb/core.py", line 1043, in ctrl_transfer
    self.__get_timeout(timeout))
  File "/home/saraseti_sunra/Desktop/checkm8/ipwndfu-master/usb/backend/libusb1.py", line 883, in ctrl_transfer
    timeout))
  File "/home/saraseti_sunra/Desktop/checkm8/ipwndfu-master/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 22] Invalid parameter

**Comment by EWouters** [comment]
This issue has been raised before in #72. Please take a look there and close this issue.

**Comment by ghost** [comment]
This also occurs to me when trying to dump SecureROM from iPhone 7 (iPhone9,1). I tried the steps from #72, but it did not help. I'm on the latest commit of ipwndfu. Since the author of this issue explicitly mentioned using an iPad mini 2, I would not close this issue until it's been confirmed to fix both iPhone X panicking AND iPad mini 2 panicking.

**Comment by jonesmith518** [comment]
iPhone 8 with 0xFF0 works
